server:
  port: 29090

spring:
  application:
    name: rabbitmq-producer
  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest

logstash.host: localhost
logstash.port: 5044

